# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe1098e839d33c3a4bc0f8cabed897b709612919f6ad9085ca8ebd75f636a3c57d9da0a80a8cbfe4d4164244fe65804bfb6be82d640df9bc4794d399f2051d7

test:
  secret_key_base: bb45227e008586da19851cb72bd6aa12795454cb44f50ed795317ad5a6610320b9da12d7883cfdcc6ca0e7213f05b9db7078525f6f03cab5d258ac53e17f76fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
